service: dino-image-server
frameworkVersion: "3"

provider:
    name: aws
    deploymentMethod: direct
    runtime: nodejs18.x
    region: eu-west-2
    iam:
    role:
        statements:
            # Allow functions to list all buckets
            - Effect: Allow
              Action: "s3:ListBucket"
              Resource: "*"
            # Allow functions to read/write objects in a bucket
            - Effect: Allow
              Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
              Resource:
                  - "arn:aws:s3:::dino-image-library/*"

functions:
    # graphql:
    #     # Make sure your file path is correct!
    #     # (e.g., if your file is in the root folder use server.graphqlHandler )
    #     # The format is: <FILENAME>.<HANDLER>
    #     handler: index.graphqlHandler
    #     events:
    #         - httpApi:
    #               path: /
    #               method: POST
    #         - httpApi:
    #               path: /
    #               method: GET
    upload:
        handler: fileUpload.handler
        events:
            - http:
                  path: /upload
                  method: post
    # function1:
    #     handler: index.handler
    #     events:
    #         - http:
    #               path: /
    #               method: get

    function2:
        handler: hello.handler
        events:
            - http:
                  path: /hello
                  method: get
