service: dino-image-server
frameworkVersion: "3"

provider:
    name: aws
    deploymentMethod: direct
    runtime: nodejs18.x
    region: eu-west-2

functions:
    graphql:
        # Make sure your file path is correct!
        # (e.g., if your file is in the root folder use server.graphqlHandler )
        # The format is: <FILENAME>.<HANDLER>
        handler: server.graphqlHandler
        events:
            - httpApi:
                  path: /
                  method: POST
            - httpApi:
                  path: /
                  method: GET
    function1:
        handler: index.handler
        events:
            - http:
                  path: /
                  method: get

    function2:
        handler: hello.handler
        events:
            - http:
                  path: /hello
                  method: get
