service: dino-image-server
frameworkVersion: "3"

provider:
    iam:
        role:
            statements:
                # Allow functions to list all buckets
                - Effect: Allow
                  Action: "s3:ListBucket"
                  Resource: "*"
                # Allow functions to read/write objects in a bucket
                - Effect: Allow
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                  Resource:
                      - "arn:aws:s3:::dino-image-library/*"
                - Effect: Allow
                  Action:
                      - dynamodb:UpdateItem
                      - dynamodb:PutItem
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                  Resource:
                      - "arn:aws:dynamodb:eu-west-2:648268634514:table/ResizeServiceTable"

                - Effect: Allow
                  Action:
                      - lambda:InvokeFunction
                  Resource:
                      - arn:aws:lambda:eu-west-2:*:*
    name: aws
    deploymentMethod: direct
    runtime: nodejs18.x
    region: eu-west-2
    apiGateway:
        binaryMediaTypes:
        - 'image/png'
        - 'image/jpeg'
        - 'multipart/form-data'

plugins:
    - serverless-offline

functions:
    graphql:
        handler: functions/graphQL.graphqlHandler
        events:
            - httpApi:
                  path: /graphql
                  method: POST
            - httpApi:
                  path: /graphql
                  method: GET
    upload:
        handler: functions/fileUpload.handler
        events:
            - http:
                  path: /upload
                  method: post
    resize:
        handler: functions/resize.handler
        events:
            - http:
                  path: /resize
                  method: get
